package de.sealcore.networking.packets;

public enum PacketType
{
    CHUNKUNLOAD,
    CHUNKUPDATE,
    ENTITYADD,
    ENTITYREMOVE,
    ENTITYUPDATEPOS,
    INVENTORYADD,
    INVENTORYSTATE,
    INVENTORYREMOVE,
    INVENTORYMOVE,
    CHUNKADD,
    MOVEINPUT,
    SETFOLLOWCAM,
    PLAYERINTERACT,
    SETHP,
    SETCOOLDOWN,
}
